### PR TITLE
WIP: Update master-e2e.yaml to use updated instance template

### PR DESCRIPTION
**Pull request by valaparthvi**
This PR updates the action with newer instance template that has no elemental zypper repo.

https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/7206427104

### CODE REVIEW

**Comment by juadk** [comment]
I think you have to rebase your PR from main to make the test green. (to pull last Chandan's code)

**Comment by valaparthvi** [comment]
> I think you have to rebase your PR from main to make the test green. (to pull last Chandan's code)

It is up to date. Now all I need is 1 approval.

**Comment by juadk** [comment]
> > I think you have to rebase your PR from main to make the test green. (to pull last Chandan's code)
> 
> It is up to date. Now all I need is 1 approval.

May you retrigger the job with the updated code? and update the description with the job's link, please.

**Comment by valaparthvi** [comment]
> > > I think you have to rebase your PR from main to make the test green. (to pull last Chandan's code)
> > 
> > 
> > It is up to date. Now all I need is 1 approval.
> 
> May you retrigger the job with the updated code? and update the description with the job's link, please.

It's done. 2.8 passed.

**Pull request closed without merging**
